"""Fix datetime_collected default 2

Revision ID: 9b33cf5ed846
Revises: e7a9a81f8057
Create Date: 2025-01-03 12:00:13.984607

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "9b33cf5ed846"
down_revision: Union[str, None] = "e7a9a81f8057"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
