"""Add run_id to run_statistics for multi-entries per run

Revision ID: de18b8228b4c
Revises: 9b33cf5ed846
Create Date: 2025-01-05 12:10:49.337886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de18b8228b4c'
down_revision: Union[str, None] = '9b33cf5ed846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Add the column with a default value
    op.add_column('run_statistics', sa.Column('run_id', sa.Integer(), server_default='0', nullable=False))

    # 2. Optional: Backfill the column with a valid run_id
    # If this requires complex logic, it may need to be handled outside the migration script.

    # 3. Remove the server default after backfilling (optional)
    with op.batch_alter_table('run_statistics') as batch_op:
        batch_op.alter_column('run_id', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_statistics', 'run_id')
    # ### end Alembic commands ###
