"""Fix datetime_collected default

Revision ID: e7a9a81f8057
Revises: ef80e3e10d88
Create Date: 2025-01-03 11:58:00.654462

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "e7a9a81f8057"
down_revision: Union[str, None] = "ef80e3e10d88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
