"""Initial migration

Revision ID: ef80e3e10d88
Revises:
Create Date: 2025-01-03 11:54:24.160858

"""
from datetime import datetime
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef80e3e10d88"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run_statistics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "datetime_collected", sa.DateTime(), default=datetime.now(), nullable=False
        ),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("wave", sa.Integer(), nullable=False),
        sa.Column("coins", sa.Float(), nullable=False),
        sa.Column("cells", sa.Integer(), nullable=False),
        sa.Column("time_spent", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("end_of_round", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_statistics")
    # ### end Alembic commands ###
